title:            z-Scale
description:      Personal website to show off a collection :)
# put your disqus here
disqus_shortname: z-scale
reading_time:     true # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             images/logo.png
#logo:             images/logo.svg # logo visible in the topbar
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

url: http://zafar.cc
# url: http://localhost:4000

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'About Me'
    url: '/about'
  - title: 'Projects'
    url: '#'
    submenu:
      - title: 'Fingerprint Viewer'
        url: '#'
      - title: 'Fingerprint Identification'
        url: '#'
      - title: 'Machine Learning Tutorials'
        url: '#'
      - title: 'BS in CS'
        url: '#'
  - title: 'Other'
    url: '#'
    submenu:
      - title: 'CTF'
        url: 'http://ctf.zafar.cc/'
      - title: 'Interview Preparation'
        # url: 'http://interview.zafar.cc/'
        url: 'http://prep.zafar.cc/'
  - title: 'All Posts'
    url: '/posts'
    submenu:
      - title: 'by Category'
        url: '/categories'
        type: 'categories'
      - title: 'by Tags'
        url: '/tags'

# Owner/author information
owner:
  name:           Zafar Takhirov
  site:           http://zafar.cc
  avatar:         images/me.jpg
  bio:            "I am a recent PhD graduate from Boston University. While my work focuses on digital design,error mitigation, and machine learning, my non-work interests range widely from information theory (go Shannon!), quantum computing, grandfather paradox, Star Trek, Little Mermaid, 'why is the grass green?', 1Q84, etc., etc., etc. If you want to talk about, well, anything - just ping me."
  email: cc.rafaz@zafar.cc
  # Twitter nick for use in Twitter cards and follow button.
  twitter: TJzafar # if no twitter in this config, the twitter follow button will be removed
  # GitHub nick for use in follow button in author block.
  github: zafartahirov

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter: TJzafar

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "github"
    url: "https://github.com/zafartahirov"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/zafartakhirov"
# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics: "UA-28089120-3"
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Los_Angeles
locale:      en_US
future:      true
highlighter: rouge
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5
not_paginated_categories:
  - sample

# if true, shows the floating share buttons
float_share: true

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  syntax_highlighter: rouge
  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1


# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
gems: [jekyll-paginate, jekyll-gist, jekyll-sitemap, jekyll-github-metadata]
